"use client";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Plus, Minus } from "lucide-react";
import { useState } from "react";

export default function FAQAccordion() {
  const faqItems = [
    {
      id: "item-1",
      question: "What does ATS-friendly mean?",
      answer:
        "An ATS-friendly resume is optimized and adheres to best practices in layout, format, and content.",
    },
    {
      id: "item-2",
      question: "Why is an ATS-friendly resume important?",
      answer:
        "ATS systems scan resumes to identify qualified candidates. An ATS-friendly format ensures your resume is properly parsed and ranked.",
    },
    {
      id: "item-3",
      question: "Are all resumes created with cvtailor.ai ATS-friendly?",
      answer:
        "Yes, all resumes generated by cvtailor.ai are created with ATS compatibility as a core feature.",
    },
    {
      id: "item-4",
      question: "How does cvtailor.ai tailor resumes to job applications?",
      answer:
        "cvtailor.ai uses AI to analyze job descriptions and optimize your resume content to match key requirements.",
    },
    {
      id: "item-5",
      question: "Can I edit my resume after its been tailored?",
      answer:
        "Yes, you can make edits to your tailored resume anytime to further customize it for specific positions.",
    },
    {
      id: "item-6",
      question: "How can I contact support if I have questions or need help?",
      answer:
        "You can reach our support team through the help center, email support, or live chat available on our website.",
    },
  ];

  const [openItem, setOpenItem] = useState<string | undefined>("item-1");

  return (
    <section className="py-20 bg-white">
      <div className="max-w-[830px] mx-auto px-4">
        {/* Header */}
        <div className="mb-14 text-center">
          <h1 className="text-2xl md:text-4xl font-bold tracking-tight text-[#1D1F2C]">
            Frequently Asked Questions
          </h1>
        </div>

        {/* FAQ Accordion */}
        <Accordion
          type="single"
          collapsible
          value={openItem}
          onValueChange={(val: string | undefined) => setOpenItem(val)}
        >
          {faqItems.map((item) => (
            <AccordionItem key={item.id} value={item.id} className="border-b question-Accordion">
              <AccordionTrigger className="py-4 font-bold text-[#333333] hover:no-underline text-lg cursor-pointer flex items-center gap-3">
                <span className="flex-1">{item.question}</span>
                <span
                  className={`ml-auto rounded-full  transition-all duration-300  text-muted-foreground ${
                    openItem === item.id
                      ? "border-white bg-orengeColor text-whiteColor"
                      : "hover:border-gray-300"
                  }`}
                >
                  {openItem === item.id ? (
                    <Minus className="w-4 h-4" />
                  ) : (
                    <Plus className="w-4 h-4" />
                  )}
                </span>
              </AccordionTrigger>
              <AccordionContent className="pb-4 text-[#4A4C56] text-sm">
                {item.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
