import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export default function FAQAccordion() {
  const faqItems = [
    {
      id: "item-1",
      question: "What does ATS-friendly mean?",
      answer:
        "An ATS-friendly resume is optimized and adheres to best practices in layout, format, and content.",
    },
    {
      id: "item-2",
      question: "Why is an ATS-friendly resume important?",
      answer:
        "ATS systems scan resumes to identify qualified candidates. An ATS-friendly format ensures your resume is properly parsed and ranked.",
    },
    {
      id: "item-3",
      question: "Are all resumes created with cvtailor.ai ATS-friendly?",
      answer:
        "Yes, all resumes generated by cvtailor.ai are created with ATS compatibility as a core feature.",
    },
    {
      id: "item-4",
      question: "How does cvtailor.ai tailor resumes to job applications?",
      answer:
        "cvtailor.ai uses AI to analyze job descriptions and optimize your resume content to match key requirements.",
    },
    {
      id: "item-5",
      question: "Can I edit my resume after its been tailored?",
      answer:
        "Yes, you can make edits to your tailored resume anytime to further customize it for specific positions.",
    },
    {
      id: "item-6",
      question: "How can I contact support if I have questions or need help?",
      answer:
        "You can reach our support team through the help center, email support, or live chat available on our website.",
    },
  ];

  return (
    <section className="py-20 bg-white">
      <div className="container">
        {/* Header */}
        <div className="mb-14 text-center">
          <h1 className="text-3xl font-bold tracking-tight text-[#1D1F2C] md:text-4xl">
            Frequently Asked Questions
          </h1>
        </div>

        {/* FAQ Accordion */}
        <Accordion type="single" collapsible defaultValue="item-1">
          {faqItems.map((item) => (
            <AccordionItem key={item.id} value={item.id} className="border-b">
              <AccordionTrigger className="py-4 font-bold text-[#333333] hover:no-underline text-lg cursor-pointer">
                {item.question}
              </AccordionTrigger>
              <AccordionContent className="pb-4 text-[#4A4C56] text-sm">
                {item.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
